name: Example action

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Minikube
      uses: manusa/actions-setup-minikube@v2.3.0
      with:
        minikube version: 'v1.16.0'
        kubernetes version: 'v1.19.2'
        github token: ${{ secrets.GITHUB_TOKEN }}
    - name: Interact with the cluster
      run: kubectl get nodes
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.6'
    - name: Install python requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Docker status
      if: ${{ always() }}
      run: service docker status
    - name: Docker images 1
      if: ${{ always() }}
      run: docker image ls
    - name: Run unittests
      if: ${{ always() }}
      run: ./run_tests.sh
    - name: Docker images 2
      if: ${{ always() }}
      run: docker image ls
    - name: pvc
      if: ${{ always() }}
      run: kubectl get pvc -n default
    - name: pv
      if: ${{ always() }}
      run: kubectl get pv
    - name: Netstat 1
      if: ${{ always() }}
      run: netstat
    - name: Print pod spec
      if: ${{ always() }}
      run: kubectl get pod -n default | grep my-input-task | awk '{print $1}' | xargs -I {} kubectl describe pod -n default {}