name: Example action

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v2
    - name: install k8s
      run: |
        curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE=777 sh -
        cat /etc/rancher/k3s/k3s.yaml
        mkdir -p ~/.kube
        cp /etc/rancher/k3s/k3s.yaml ~/.kube/config
        /etc/rancher/k3s/registries.yaml
    - name: add registry
      run: |
        mirrors:
          "192.168.2.110:5055":
            endpoint:
              - "http://192.168.2.110:5055"
        kubectl cluster-info
        kubectl create deployment --image nginx my-nginx
        kubectl get pods
        kubectl get nodes
    - name: example tests
      run: |
        kubectl cluster-info
        kubectl create deployment --image nginx my-nginx
        kubectl get pods
        kubectl get nodes
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.6'
    - name: Install python requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Docker status
      if: ${{ always() }}
      run: service docker status
    - name: Docker images 1
      if: ${{ always() }}
      run: docker image ls
    - name: Run unittests
      if: ${{ always() }}
      run: ./run_tests.sh
    - name: Docker images 2
      if: ${{ always() }}
      run: docker image ls
    - name: pvc
      if: ${{ always() }}
      run: kubectl get pvc -n default
    - name: pv
      if: ${{ always() }}
      run: kubectl get pv
    - name: Netstat 1
      if: ${{ always() }}
      run: netstat
    - name: Print pod spec
      if: ${{ always() }}
      run: kubectl get pod -n default | grep my-input-task | awk '{print $1}' | xargs -I {} kubectl describe pod -n default {}
    - name: Run image
      if: ${{ always() }}
      run: docker run docker.io/rancher/my_python_task_img
    - name: Run check img
      if: ${{ always() }}
      run: docker ps